namespace DVLD_Project.Users
{
    partial class frmAddEditUser
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmAddEditUser));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tcAddEditUser = new Bunifu.UI.WinForms.BunifuPages();
            this.tpSelectPerson = new System.Windows.Forms.TabPage();
            this.btnClose1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNext = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblAddNewUser = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblSelectPerson = new Bunifu.UI.WinForms.BunifuLabel();
            this.tpLoginInfo = new System.Windows.Forms.TabPage();
            this.btnPrevious = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClose2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblPersonIDValue = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.lblManageApplications = new Bunifu.UI.WinForms.BunifuLabel();
            this.chkManageApplications = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.chkManageUsers = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.lblManagePeople = new Bunifu.UI.WinForms.BunifuLabel();
            this.chkManagePeople = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.txtConfirmPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblConfirmPassword = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblUserIdValue = new Bunifu.UI.WinForms.BunifuLabel();
            this.chkIsActive = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPassword = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblUsername = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblUserID = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblAddNewUser2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.ucPersonInfoWithFilter1 = new DVLD_Project.People.Controls.ucPersonInfoWithFilter();
            this.tcAddEditUser.SuspendLayout();
            this.tpSelectPerson.SuspendLayout();
            this.tpLoginInfo.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tcAddEditUser
            // 
            this.tcAddEditUser.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.tcAddEditUser.AllowTransitions = false;
            this.tcAddEditUser.Controls.Add(this.tpSelectPerson);
            this.tcAddEditUser.Controls.Add(this.tpLoginInfo);
            this.tcAddEditUser.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tcAddEditUser.Location = new System.Drawing.Point(0, 0);
            this.tcAddEditUser.Multiline = true;
            this.tcAddEditUser.Name = "tcAddEditUser";
            this.tcAddEditUser.Page = this.tpSelectPerson;
            this.tcAddEditUser.PageIndex = 0;
            this.tcAddEditUser.PageName = "tpSelectPerson";
            this.tcAddEditUser.PageTitle = "PersonInfo";
            this.tcAddEditUser.SelectedIndex = 0;
            this.tcAddEditUser.Size = new System.Drawing.Size(759, 601);
            this.tcAddEditUser.TabIndex = 0;
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.tcAddEditUser.Transition = animation1;
            this.tcAddEditUser.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            this.tcAddEditUser.SelectedIndexChanged += new System.EventHandler(this.tcAddEditUser_SelectedIndexChanged);
            // 
            // tpSelectPerson
            // 
            this.tpSelectPerson.BackColor = System.Drawing.Color.White;
            this.tpSelectPerson.Controls.Add(this.btnClose1);
            this.tpSelectPerson.Controls.Add(this.btnNext);
            this.tpSelectPerson.Controls.Add(this.lblAddNewUser);
            this.tpSelectPerson.Controls.Add(this.lblSelectPerson);
            this.tpSelectPerson.Controls.Add(this.ucPersonInfoWithFilter1);
            this.tpSelectPerson.Location = new System.Drawing.Point(4, 4);
            this.tpSelectPerson.Name = "tpSelectPerson";
            this.tpSelectPerson.Padding = new System.Windows.Forms.Padding(3);
            this.tpSelectPerson.Size = new System.Drawing.Size(751, 575);
            this.tpSelectPerson.TabIndex = 0;
            this.tpSelectPerson.Text = "PersonInfo";
            // 
            // btnClose1
            // 
            this.btnClose1.AllowAnimations = true;
            this.btnClose1.AllowMouseEffects = true;
            this.btnClose1.AllowToggling = false;
            this.btnClose1.AnimationSpeed = 200;
            this.btnClose1.AutoGenerateColors = false;
            this.btnClose1.AutoRoundBorders = true;
            this.btnClose1.AutoSizeLeftIcon = true;
            this.btnClose1.AutoSizeRightIcon = true;
            this.btnClose1.BackColor = System.Drawing.Color.Transparent;
            this.btnClose1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnClose1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose1.BackgroundImage")));
            this.btnClose1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose1.ButtonText = "Close";
            this.btnClose1.ButtonTextMarginLeft = 0;
            this.btnClose1.ColorContrastOnClick = 45;
            this.btnClose1.ColorContrastOnHover = 45;
            this.btnClose1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnClose1.CustomizableEdges = borderEdges1;
            this.btnClose1.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnClose1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose1.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnClose1.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnClose1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose1.ForeColor = System.Drawing.Color.White;
            this.btnClose1.IconLeft = global::DVLD_Project.Properties.Resources.icons8_cancel_32;
            this.btnClose1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose1.IconMarginLeft = 11;
            this.btnClose1.IconPadding = 7;
            this.btnClose1.IconRight = null;
            this.btnClose1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose1.IconSize = 25;
            this.btnClose1.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnClose1.IdleBorderRadius = 0;
            this.btnClose1.IdleBorderThickness = 0;
            this.btnClose1.IdleFillColor = System.Drawing.Color.Empty;
            this.btnClose1.IdleIconLeftImage = global::DVLD_Project.Properties.Resources.icons8_cancel_32;
            this.btnClose1.IdleIconRightImage = null;
            this.btnClose1.IndicateFocus = false;
            this.btnClose1.Location = new System.Drawing.Point(22, 522);
            this.btnClose1.Name = "btnClose1";
            this.btnClose1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose1.OnDisabledState.BorderRadius = 47;
            this.btnClose1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose1.OnDisabledState.BorderThickness = 1;
            this.btnClose1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose1.OnDisabledState.IconLeftImage = null;
            this.btnClose1.OnDisabledState.IconRightImage = null;
            this.btnClose1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnClose1.onHoverState.BorderRadius = 47;
            this.btnClose1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose1.onHoverState.BorderThickness = 1;
            this.btnClose1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnClose1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose1.onHoverState.IconLeftImage = null;
            this.btnClose1.onHoverState.IconRightImage = null;
            this.btnClose1.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnClose1.OnIdleState.BorderRadius = 47;
            this.btnClose1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose1.OnIdleState.BorderThickness = 1;
            this.btnClose1.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnClose1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose1.OnIdleState.IconLeftImage = global::DVLD_Project.Properties.Resources.icons8_cancel_32;
            this.btnClose1.OnIdleState.IconRightImage = null;
            this.btnClose1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose1.OnPressedState.BorderRadius = 47;
            this.btnClose1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose1.OnPressedState.BorderThickness = 1;
            this.btnClose1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose1.OnPressedState.IconLeftImage = null;
            this.btnClose1.OnPressedState.IconRightImage = null;
            this.btnClose1.Size = new System.Drawing.Size(150, 47);
            this.btnClose1.TabIndex = 4;
            this.btnClose1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose1.TextMarginLeft = 0;
            this.btnClose1.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose1.UseDefaultRadiusAndThickness = true;
            this.btnClose1.Click += new System.EventHandler(this.btnClose1_Click);
            // 
            // btnNext
            // 
            this.btnNext.AllowAnimations = true;
            this.btnNext.AllowMouseEffects = true;
            this.btnNext.AllowToggling = false;
            this.btnNext.AnimationSpeed = 200;
            this.btnNext.AutoGenerateColors = false;
            this.btnNext.AutoRoundBorders = true;
            this.btnNext.AutoSizeLeftIcon = true;
            this.btnNext.AutoSizeRightIcon = true;
            this.btnNext.BackColor = System.Drawing.Color.Transparent;
            this.btnNext.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnNext.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNext.BackgroundImage")));
            this.btnNext.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.ButtonText = "Next";
            this.btnNext.ButtonTextMarginLeft = 0;
            this.btnNext.ColorContrastOnClick = 45;
            this.btnNext.ColorContrastOnHover = 45;
            this.btnNext.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnNext.CustomizableEdges = borderEdges2;
            this.btnNext.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNext.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNext.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnNext.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnNext.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNext.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNext.ForeColor = System.Drawing.Color.White;
            this.btnNext.IconLeft = null;
            this.btnNext.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNext.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNext.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNext.IconMarginLeft = 11;
            this.btnNext.IconPadding = 7;
            this.btnNext.IconRight = global::DVLD_Project.Properties.Resources.icons8_next_32;
            this.btnNext.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNext.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNext.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNext.IconSize = 25;
            this.btnNext.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnNext.IdleBorderRadius = 0;
            this.btnNext.IdleBorderThickness = 0;
            this.btnNext.IdleFillColor = System.Drawing.Color.Empty;
            this.btnNext.IdleIconLeftImage = null;
            this.btnNext.IdleIconRightImage = global::DVLD_Project.Properties.Resources.icons8_next_32;
            this.btnNext.IndicateFocus = false;
            this.btnNext.Location = new System.Drawing.Point(582, 522);
            this.btnNext.Name = "btnNext";
            this.btnNext.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNext.OnDisabledState.BorderRadius = 47;
            this.btnNext.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnDisabledState.BorderThickness = 1;
            this.btnNext.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNext.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNext.OnDisabledState.IconLeftImage = null;
            this.btnNext.OnDisabledState.IconRightImage = null;
            this.btnNext.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnNext.onHoverState.BorderRadius = 47;
            this.btnNext.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.onHoverState.BorderThickness = 1;
            this.btnNext.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnNext.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNext.onHoverState.IconLeftImage = null;
            this.btnNext.onHoverState.IconRightImage = null;
            this.btnNext.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.btnNext.OnIdleState.BorderRadius = 47;
            this.btnNext.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnIdleState.BorderThickness = 1;
            this.btnNext.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.btnNext.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNext.OnIdleState.IconLeftImage = null;
            this.btnNext.OnIdleState.IconRightImage = global::DVLD_Project.Properties.Resources.icons8_next_32;
            this.btnNext.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNext.OnPressedState.BorderRadius = 47;
            this.btnNext.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnPressedState.BorderThickness = 1;
            this.btnNext.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNext.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNext.OnPressedState.IconLeftImage = null;
            this.btnNext.OnPressedState.IconRightImage = null;
            this.btnNext.Size = new System.Drawing.Size(150, 47);
            this.btnNext.TabIndex = 3;
            this.btnNext.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNext.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNext.TextMarginLeft = 0;
            this.btnNext.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNext.UseDefaultRadiusAndThickness = true;
            this.btnNext.Click += new System.EventHandler(this.btnNext_Click);
            // 
            // lblAddNewUser
            // 
            this.lblAddNewUser.AllowParentOverrides = false;
            this.lblAddNewUser.AutoEllipsis = false;
            this.lblAddNewUser.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblAddNewUser.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblAddNewUser.Font = new System.Drawing.Font("Segoe UI", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAddNewUser.ForeColor = System.Drawing.Color.DodgerBlue;
            this.lblAddNewUser.Location = new System.Drawing.Point(266, 37);
            this.lblAddNewUser.Name = "lblAddNewUser";
            this.lblAddNewUser.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblAddNewUser.Size = new System.Drawing.Size(196, 40);
            this.lblAddNewUser.TabIndex = 2;
            this.lblAddNewUser.Text = "Add New User";
            this.lblAddNewUser.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblAddNewUser.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblSelectPerson
            // 
            this.lblSelectPerson.AllowParentOverrides = false;
            this.lblSelectPerson.AutoEllipsis = false;
            this.lblSelectPerson.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblSelectPerson.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblSelectPerson.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSelectPerson.Location = new System.Drawing.Point(265, 90);
            this.lblSelectPerson.Name = "lblSelectPerson";
            this.lblSelectPerson.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblSelectPerson.Size = new System.Drawing.Size(199, 20);
            this.lblSelectPerson.TabIndex = 1;
            this.lblSelectPerson.Text = "Please choose the person first.";
            this.lblSelectPerson.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblSelectPerson.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tpLoginInfo
            // 
            this.tpLoginInfo.BackColor = System.Drawing.Color.White;
            this.tpLoginInfo.Controls.Add(this.btnPrevious);
            this.tpLoginInfo.Controls.Add(this.btnClose2);
            this.tpLoginInfo.Controls.Add(this.btnSave);
            this.tpLoginInfo.Controls.Add(this.lblPersonIDValue);
            this.tpLoginInfo.Controls.Add(this.bunifuLabel6);
            this.tpLoginInfo.Controls.Add(this.bunifuGroupBox1);
            this.tpLoginInfo.Controls.Add(this.txtConfirmPassword);
            this.tpLoginInfo.Controls.Add(this.lblConfirmPassword);
            this.tpLoginInfo.Controls.Add(this.txtPassword);
            this.tpLoginInfo.Controls.Add(this.txtUsername);
            this.tpLoginInfo.Controls.Add(this.lblUserIdValue);
            this.tpLoginInfo.Controls.Add(this.chkIsActive);
            this.tpLoginInfo.Controls.Add(this.bunifuLabel2);
            this.tpLoginInfo.Controls.Add(this.lblPassword);
            this.tpLoginInfo.Controls.Add(this.lblUsername);
            this.tpLoginInfo.Controls.Add(this.lblUserID);
            this.tpLoginInfo.Controls.Add(this.lblAddNewUser2);
            this.tpLoginInfo.Location = new System.Drawing.Point(4, 4);
            this.tpLoginInfo.Name = "tpLoginInfo";
            this.tpLoginInfo.Padding = new System.Windows.Forms.Padding(3);
            this.tpLoginInfo.Size = new System.Drawing.Size(751, 575);
            this.tpLoginInfo.TabIndex = 1;
            this.tpLoginInfo.Text = "LoginInfo";
            // 
            // btnPrevious
            // 
            this.btnPrevious.AllowAnimations = true;
            this.btnPrevious.AllowMouseEffects = true;
            this.btnPrevious.AllowToggling = false;
            this.btnPrevious.AnimationSpeed = 200;
            this.btnPrevious.AutoGenerateColors = false;
            this.btnPrevious.AutoRoundBorders = true;
            this.btnPrevious.AutoSizeLeftIcon = true;
            this.btnPrevious.AutoSizeRightIcon = true;
            this.btnPrevious.BackColor = System.Drawing.Color.Transparent;
            this.btnPrevious.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnPrevious.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPrevious.BackgroundImage")));
            this.btnPrevious.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrevious.ButtonText = "Previous";
            this.btnPrevious.ButtonTextMarginLeft = 0;
            this.btnPrevious.ColorContrastOnClick = 45;
            this.btnPrevious.ColorContrastOnHover = 45;
            this.btnPrevious.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnPrevious.CustomizableEdges = borderEdges3;
            this.btnPrevious.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPrevious.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrevious.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnPrevious.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnPrevious.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPrevious.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrevious.ForeColor = System.Drawing.Color.White;
            this.btnPrevious.IconLeft = global::DVLD_Project.Properties.Resources.icons8_previous_48;
            this.btnPrevious.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrevious.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrevious.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPrevious.IconMarginLeft = 11;
            this.btnPrevious.IconPadding = 8;
            this.btnPrevious.IconRight = null;
            this.btnPrevious.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrevious.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrevious.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPrevious.IconSize = 25;
            this.btnPrevious.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnPrevious.IdleBorderRadius = 0;
            this.btnPrevious.IdleBorderThickness = 0;
            this.btnPrevious.IdleFillColor = System.Drawing.Color.Empty;
            this.btnPrevious.IdleIconLeftImage = global::DVLD_Project.Properties.Resources.icons8_previous_48;
            this.btnPrevious.IdleIconRightImage = null;
            this.btnPrevious.IndicateFocus = false;
            this.btnPrevious.Location = new System.Drawing.Point(23, 508);
            this.btnPrevious.Name = "btnPrevious";
            this.btnPrevious.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrevious.OnDisabledState.BorderRadius = 47;
            this.btnPrevious.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrevious.OnDisabledState.BorderThickness = 1;
            this.btnPrevious.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrevious.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrevious.OnDisabledState.IconLeftImage = null;
            this.btnPrevious.OnDisabledState.IconRightImage = null;
            this.btnPrevious.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPrevious.onHoverState.BorderRadius = 47;
            this.btnPrevious.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrevious.onHoverState.BorderThickness = 1;
            this.btnPrevious.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPrevious.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPrevious.onHoverState.IconLeftImage = null;
            this.btnPrevious.onHoverState.IconRightImage = null;
            this.btnPrevious.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.btnPrevious.OnIdleState.BorderRadius = 47;
            this.btnPrevious.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrevious.OnIdleState.BorderThickness = 1;
            this.btnPrevious.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.btnPrevious.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPrevious.OnIdleState.IconLeftImage = global::DVLD_Project.Properties.Resources.icons8_previous_48;
            this.btnPrevious.OnIdleState.IconRightImage = null;
            this.btnPrevious.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPrevious.OnPressedState.BorderRadius = 47;
            this.btnPrevious.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrevious.OnPressedState.BorderThickness = 1;
            this.btnPrevious.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPrevious.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPrevious.OnPressedState.IconLeftImage = null;
            this.btnPrevious.OnPressedState.IconRightImage = null;
            this.btnPrevious.Size = new System.Drawing.Size(150, 47);
            this.btnPrevious.TabIndex = 19;
            this.btnPrevious.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPrevious.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPrevious.TextMarginLeft = 0;
            this.btnPrevious.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPrevious.UseDefaultRadiusAndThickness = true;
            this.btnPrevious.Click += new System.EventHandler(this.btnPrevious_Click);
            // 
            // btnClose2
            // 
            this.btnClose2.AllowAnimations = true;
            this.btnClose2.AllowMouseEffects = true;
            this.btnClose2.AllowToggling = false;
            this.btnClose2.AnimationSpeed = 200;
            this.btnClose2.AutoGenerateColors = false;
            this.btnClose2.AutoRoundBorders = true;
            this.btnClose2.AutoSizeLeftIcon = true;
            this.btnClose2.AutoSizeRightIcon = true;
            this.btnClose2.BackColor = System.Drawing.Color.Transparent;
            this.btnClose2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnClose2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose2.BackgroundImage")));
            this.btnClose2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose2.ButtonText = "Close";
            this.btnClose2.ButtonTextMarginLeft = 0;
            this.btnClose2.ColorContrastOnClick = 45;
            this.btnClose2.ColorContrastOnHover = 45;
            this.btnClose2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnClose2.CustomizableEdges = borderEdges4;
            this.btnClose2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose2.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnClose2.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnClose2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose2.ForeColor = System.Drawing.Color.White;
            this.btnClose2.IconLeft = global::DVLD_Project.Properties.Resources.icons8_cancel_32;
            this.btnClose2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose2.IconMarginLeft = 11;
            this.btnClose2.IconPadding = 7;
            this.btnClose2.IconRight = null;
            this.btnClose2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose2.IconSize = 25;
            this.btnClose2.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnClose2.IdleBorderRadius = 0;
            this.btnClose2.IdleBorderThickness = 0;
            this.btnClose2.IdleFillColor = System.Drawing.Color.Empty;
            this.btnClose2.IdleIconLeftImage = global::DVLD_Project.Properties.Resources.icons8_cancel_32;
            this.btnClose2.IdleIconRightImage = null;
            this.btnClose2.IndicateFocus = false;
            this.btnClose2.Location = new System.Drawing.Point(593, 508);
            this.btnClose2.Name = "btnClose2";
            this.btnClose2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose2.OnDisabledState.BorderRadius = 47;
            this.btnClose2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose2.OnDisabledState.BorderThickness = 1;
            this.btnClose2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose2.OnDisabledState.IconLeftImage = null;
            this.btnClose2.OnDisabledState.IconRightImage = null;
            this.btnClose2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnClose2.onHoverState.BorderRadius = 47;
            this.btnClose2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose2.onHoverState.BorderThickness = 1;
            this.btnClose2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnClose2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose2.onHoverState.IconLeftImage = null;
            this.btnClose2.onHoverState.IconRightImage = null;
            this.btnClose2.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnClose2.OnIdleState.BorderRadius = 47;
            this.btnClose2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose2.OnIdleState.BorderThickness = 1;
            this.btnClose2.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnClose2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose2.OnIdleState.IconLeftImage = global::DVLD_Project.Properties.Resources.icons8_cancel_32;
            this.btnClose2.OnIdleState.IconRightImage = null;
            this.btnClose2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose2.OnPressedState.BorderRadius = 47;
            this.btnClose2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose2.OnPressedState.BorderThickness = 1;
            this.btnClose2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose2.OnPressedState.IconLeftImage = null;
            this.btnClose2.OnPressedState.IconRightImage = null;
            this.btnClose2.Size = new System.Drawing.Size(150, 47);
            this.btnClose2.TabIndex = 18;
            this.btnClose2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose2.TextMarginLeft = 0;
            this.btnClose2.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose2.UseDefaultRadiusAndThickness = true;
            this.btnClose2.Click += new System.EventHandler(this.btnClose2_Click);
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = true;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges5;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSave.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeft = global::DVLD_Project.Properties.Resources.icons8_save_32;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 8;
            this.btnSave.IconRight = null;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSave.IdleBorderRadius = 0;
            this.btnSave.IdleBorderThickness = 0;
            this.btnSave.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSave.IdleIconLeftImage = global::DVLD_Project.Properties.Resources.icons8_save_32;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(308, 508);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 47;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 47;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.Green;
            this.btnSave.OnIdleState.BorderRadius = 47;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.Green;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = global::DVLD_Project.Properties.Resources.icons8_save_32;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 47;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(150, 47);
            this.btnSave.TabIndex = 17;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // lblPersonIDValue
            // 
            this.lblPersonIDValue.AllowParentOverrides = false;
            this.lblPersonIDValue.AutoEllipsis = false;
            this.lblPersonIDValue.CursorType = null;
            this.lblPersonIDValue.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPersonIDValue.Location = new System.Drawing.Point(217, 137);
            this.lblPersonIDValue.Name = "lblPersonIDValue";
            this.lblPersonIDValue.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPersonIDValue.Size = new System.Drawing.Size(18, 17);
            this.lblPersonIDValue.TabIndex = 16;
            this.lblPersonIDValue.Text = "???";
            this.lblPersonIDValue.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPersonIDValue.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(112, 137);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(64, 17);
            this.bunifuLabel6.TabIndex = 15;
            this.bunifuLabel6.Text = "Person ID:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 5;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.lblManageApplications);
            this.bunifuGroupBox1.Controls.Add(this.chkManageApplications);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel5);
            this.bunifuGroupBox1.Controls.Add(this.chkManageUsers);
            this.bunifuGroupBox1.Controls.Add(this.lblManagePeople);
            this.bunifuGroupBox1.Controls.Add(this.chkManagePeople);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(86, 346);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(376, 128);
            this.bunifuGroupBox1.TabIndex = 14;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Permissions:";
            // 
            // lblManageApplications
            // 
            this.lblManageApplications.AllowParentOverrides = false;
            this.lblManageApplications.AutoEllipsis = false;
            this.lblManageApplications.CursorType = null;
            this.lblManageApplications.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblManageApplications.Location = new System.Drawing.Point(249, 45);
            this.lblManageApplications.Name = "lblManageApplications";
            this.lblManageApplications.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblManageApplications.Size = new System.Drawing.Size(115, 15);
            this.lblManageApplications.TabIndex = 20;
            this.lblManageApplications.Text = "Manage Applications.";
            this.lblManageApplications.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblManageApplications.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // chkManageApplications
            // 
            this.chkManageApplications.AllowBindingControlAnimation = true;
            this.chkManageApplications.AllowBindingControlColorChanges = false;
            this.chkManageApplications.AllowBindingControlLocation = true;
            this.chkManageApplications.AllowCheckBoxAnimation = false;
            this.chkManageApplications.AllowCheckmarkAnimation = true;
            this.chkManageApplications.AllowOnHoverStates = true;
            this.chkManageApplications.AutoCheck = true;
            this.chkManageApplications.BackColor = System.Drawing.Color.Transparent;
            this.chkManageApplications.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chkManageApplications.BackgroundImage")));
            this.chkManageApplications.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chkManageApplications.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chkManageApplications.BorderRadius = 12;
            this.chkManageApplications.Checked = false;
            this.chkManageApplications.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.chkManageApplications.Cursor = System.Windows.Forms.Cursors.Default;
            this.chkManageApplications.CustomCheckmarkImage = null;
            this.chkManageApplications.Location = new System.Drawing.Point(222, 42);
            this.chkManageApplications.MinimumSize = new System.Drawing.Size(17, 17);
            this.chkManageApplications.Name = "chkManageApplications";
            this.chkManageApplications.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.chkManageApplications.OnCheck.BorderRadius = 12;
            this.chkManageApplications.OnCheck.BorderThickness = 2;
            this.chkManageApplications.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.chkManageApplications.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chkManageApplications.OnCheck.CheckmarkThickness = 2;
            this.chkManageApplications.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chkManageApplications.OnDisable.BorderRadius = 12;
            this.chkManageApplications.OnDisable.BorderThickness = 2;
            this.chkManageApplications.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManageApplications.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chkManageApplications.OnDisable.CheckmarkThickness = 2;
            this.chkManageApplications.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManageApplications.OnHoverChecked.BorderRadius = 12;
            this.chkManageApplications.OnHoverChecked.BorderThickness = 2;
            this.chkManageApplications.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManageApplications.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chkManageApplications.OnHoverChecked.CheckmarkThickness = 2;
            this.chkManageApplications.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManageApplications.OnHoverUnchecked.BorderRadius = 12;
            this.chkManageApplications.OnHoverUnchecked.BorderThickness = 1;
            this.chkManageApplications.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManageApplications.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chkManageApplications.OnUncheck.BorderRadius = 12;
            this.chkManageApplications.OnUncheck.BorderThickness = 1;
            this.chkManageApplications.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManageApplications.Size = new System.Drawing.Size(21, 21);
            this.chkManageApplications.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chkManageApplications.TabIndex = 19;
            this.chkManageApplications.ThreeState = false;
            this.chkManageApplications.ToolTipText = null;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(37, 75);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(77, 15);
            this.bunifuLabel5.TabIndex = 18;
            this.bunifuLabel5.Text = "Manage Users.";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // chkManageUsers
            // 
            this.chkManageUsers.AllowBindingControlAnimation = true;
            this.chkManageUsers.AllowBindingControlColorChanges = false;
            this.chkManageUsers.AllowBindingControlLocation = true;
            this.chkManageUsers.AllowCheckBoxAnimation = false;
            this.chkManageUsers.AllowCheckmarkAnimation = true;
            this.chkManageUsers.AllowOnHoverStates = true;
            this.chkManageUsers.AutoCheck = true;
            this.chkManageUsers.BackColor = System.Drawing.Color.Transparent;
            this.chkManageUsers.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chkManageUsers.BackgroundImage")));
            this.chkManageUsers.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chkManageUsers.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chkManageUsers.BorderRadius = 12;
            this.chkManageUsers.Checked = false;
            this.chkManageUsers.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.chkManageUsers.Cursor = System.Windows.Forms.Cursors.Default;
            this.chkManageUsers.CustomCheckmarkImage = null;
            this.chkManageUsers.Location = new System.Drawing.Point(10, 72);
            this.chkManageUsers.MinimumSize = new System.Drawing.Size(17, 17);
            this.chkManageUsers.Name = "chkManageUsers";
            this.chkManageUsers.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.chkManageUsers.OnCheck.BorderRadius = 12;
            this.chkManageUsers.OnCheck.BorderThickness = 2;
            this.chkManageUsers.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.chkManageUsers.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chkManageUsers.OnCheck.CheckmarkThickness = 2;
            this.chkManageUsers.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chkManageUsers.OnDisable.BorderRadius = 12;
            this.chkManageUsers.OnDisable.BorderThickness = 2;
            this.chkManageUsers.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManageUsers.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chkManageUsers.OnDisable.CheckmarkThickness = 2;
            this.chkManageUsers.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManageUsers.OnHoverChecked.BorderRadius = 12;
            this.chkManageUsers.OnHoverChecked.BorderThickness = 2;
            this.chkManageUsers.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManageUsers.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chkManageUsers.OnHoverChecked.CheckmarkThickness = 2;
            this.chkManageUsers.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManageUsers.OnHoverUnchecked.BorderRadius = 12;
            this.chkManageUsers.OnHoverUnchecked.BorderThickness = 1;
            this.chkManageUsers.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManageUsers.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chkManageUsers.OnUncheck.BorderRadius = 12;
            this.chkManageUsers.OnUncheck.BorderThickness = 1;
            this.chkManageUsers.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManageUsers.Size = new System.Drawing.Size(21, 21);
            this.chkManageUsers.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chkManageUsers.TabIndex = 17;
            this.chkManageUsers.ThreeState = false;
            this.chkManageUsers.ToolTipText = null;
            // 
            // lblManagePeople
            // 
            this.lblManagePeople.AllowParentOverrides = false;
            this.lblManagePeople.AutoEllipsis = false;
            this.lblManagePeople.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblManagePeople.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblManagePeople.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblManagePeople.Location = new System.Drawing.Point(37, 42);
            this.lblManagePeople.Name = "lblManagePeople";
            this.lblManagePeople.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblManagePeople.Size = new System.Drawing.Size(85, 15);
            this.lblManagePeople.TabIndex = 16;
            this.lblManagePeople.Text = "Manage People.";
            this.lblManagePeople.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblManagePeople.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // chkManagePeople
            // 
            this.chkManagePeople.AllowBindingControlAnimation = true;
            this.chkManagePeople.AllowBindingControlColorChanges = false;
            this.chkManagePeople.AllowBindingControlLocation = true;
            this.chkManagePeople.AllowCheckBoxAnimation = false;
            this.chkManagePeople.AllowCheckmarkAnimation = true;
            this.chkManagePeople.AllowOnHoverStates = true;
            this.chkManagePeople.AutoCheck = true;
            this.chkManagePeople.BackColor = System.Drawing.Color.Transparent;
            this.chkManagePeople.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chkManagePeople.BackgroundImage")));
            this.chkManagePeople.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chkManagePeople.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chkManagePeople.BorderRadius = 12;
            this.chkManagePeople.Checked = false;
            this.chkManagePeople.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.chkManagePeople.Cursor = System.Windows.Forms.Cursors.Default;
            this.chkManagePeople.CustomCheckmarkImage = null;
            this.chkManagePeople.Location = new System.Drawing.Point(10, 39);
            this.chkManagePeople.MinimumSize = new System.Drawing.Size(17, 17);
            this.chkManagePeople.Name = "chkManagePeople";
            this.chkManagePeople.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.chkManagePeople.OnCheck.BorderRadius = 12;
            this.chkManagePeople.OnCheck.BorderThickness = 2;
            this.chkManagePeople.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.chkManagePeople.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chkManagePeople.OnCheck.CheckmarkThickness = 2;
            this.chkManagePeople.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chkManagePeople.OnDisable.BorderRadius = 12;
            this.chkManagePeople.OnDisable.BorderThickness = 2;
            this.chkManagePeople.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManagePeople.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chkManagePeople.OnDisable.CheckmarkThickness = 2;
            this.chkManagePeople.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManagePeople.OnHoverChecked.BorderRadius = 12;
            this.chkManagePeople.OnHoverChecked.BorderThickness = 2;
            this.chkManagePeople.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManagePeople.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chkManagePeople.OnHoverChecked.CheckmarkThickness = 2;
            this.chkManagePeople.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkManagePeople.OnHoverUnchecked.BorderRadius = 12;
            this.chkManagePeople.OnHoverUnchecked.BorderThickness = 1;
            this.chkManagePeople.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManagePeople.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chkManagePeople.OnUncheck.BorderRadius = 12;
            this.chkManagePeople.OnUncheck.BorderThickness = 1;
            this.chkManagePeople.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkManagePeople.Size = new System.Drawing.Size(21, 21);
            this.chkManagePeople.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chkManagePeople.TabIndex = 15;
            this.chkManagePeople.ThreeState = false;
            this.chkManagePeople.ToolTipText = null;
            // 
            // txtConfirmPassword
            // 
            this.txtConfirmPassword.AcceptsReturn = false;
            this.txtConfirmPassword.AcceptsTab = false;
            this.txtConfirmPassword.AnimationSpeed = 200;
            this.txtConfirmPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtConfirmPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtConfirmPassword.AutoSizeHeight = true;
            this.txtConfirmPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtConfirmPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtConfirmPassword.BackgroundImage")));
            this.txtConfirmPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtConfirmPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtConfirmPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtConfirmPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtConfirmPassword.BorderRadius = 15;
            this.txtConfirmPassword.BorderThickness = 1;
            this.txtConfirmPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtConfirmPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtConfirmPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtConfirmPassword.DefaultText = "";
            this.txtConfirmPassword.FillColor = System.Drawing.Color.White;
            this.txtConfirmPassword.HideSelection = true;
            this.txtConfirmPassword.IconLeft = global::DVLD_Project.Properties.Resources.icons8_sign_in_form_password_40;
            this.txtConfirmPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmPassword.IconPadding = 7;
            this.txtConfirmPassword.IconRight = global::DVLD_Project.Properties.Resources.icons8_show_password_48;
            this.txtConfirmPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmPassword.Lines = new string[0];
            this.txtConfirmPassword.Location = new System.Drawing.Point(217, 250);
            this.txtConfirmPassword.MaxLength = 32767;
            this.txtConfirmPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtConfirmPassword.Modified = false;
            this.txtConfirmPassword.Multiline = false;
            this.txtConfirmPassword.Name = "txtConfirmPassword";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmPassword.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtConfirmPassword.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmPassword.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtConfirmPassword.OnIdleState = stateProperties4;
            this.txtConfirmPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtConfirmPassword.PasswordChar = '\0';
            this.txtConfirmPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtConfirmPassword.PlaceholderText = "Confirm Password";
            this.txtConfirmPassword.ReadOnly = false;
            this.txtConfirmPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtConfirmPassword.SelectedText = "";
            this.txtConfirmPassword.SelectionLength = 0;
            this.txtConfirmPassword.SelectionStart = 0;
            this.txtConfirmPassword.ShortcutsEnabled = true;
            this.txtConfirmPassword.Size = new System.Drawing.Size(178, 39);
            this.txtConfirmPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtConfirmPassword.TabIndex = 13;
            this.txtConfirmPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtConfirmPassword.TextMarginBottom = 0;
            this.txtConfirmPassword.TextMarginLeft = 3;
            this.txtConfirmPassword.TextMarginTop = 1;
            this.txtConfirmPassword.TextPlaceholder = "Confirm Password";
            this.txtConfirmPassword.UseSystemPasswordChar = true;
            this.txtConfirmPassword.WordWrap = true;
            // 
            // lblConfirmPassword
            // 
            this.lblConfirmPassword.AllowParentOverrides = false;
            this.lblConfirmPassword.AutoEllipsis = false;
            this.lblConfirmPassword.CursorType = null;
            this.lblConfirmPassword.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblConfirmPassword.Location = new System.Drawing.Point(60, 261);
            this.lblConfirmPassword.Name = "lblConfirmPassword";
            this.lblConfirmPassword.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblConfirmPassword.Size = new System.Drawing.Size(116, 17);
            this.lblConfirmPassword.TabIndex = 12;
            this.lblConfirmPassword.Text = "Confirm Password:";
            this.lblConfirmPassword.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblConfirmPassword.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtPassword
            // 
            this.txtPassword.AcceptsReturn = false;
            this.txtPassword.AcceptsTab = false;
            this.txtPassword.AnimationSpeed = 200;
            this.txtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword.AutoSizeHeight = true;
            this.txtPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword.BackgroundImage")));
            this.txtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPassword.BorderRadius = 15;
            this.txtPassword.BorderThickness = 1;
            this.txtPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPassword.DefaultText = "";
            this.txtPassword.FillColor = System.Drawing.Color.White;
            this.txtPassword.HideSelection = true;
            this.txtPassword.IconLeft = global::DVLD_Project.Properties.Resources.icons8_sign_in_form_password_40;
            this.txtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.IconPadding = 7;
            this.txtPassword.IconRight = global::DVLD_Project.Properties.Resources.icons8_show_password_48;
            this.txtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.Lines = new string[0];
            this.txtPassword.Location = new System.Drawing.Point(217, 205);
            this.txtPassword.MaxLength = 32767;
            this.txtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPassword.Modified = false;
            this.txtPassword.Multiline = false;
            this.txtPassword.Name = "txtPassword";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnIdleState = stateProperties8;
            this.txtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtPassword.PasswordChar = '\0';
            this.txtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword.PlaceholderText = "Enter Password";
            this.txtPassword.ReadOnly = false;
            this.txtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(178, 39);
            this.txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword.TabIndex = 11;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TextMarginBottom = 0;
            this.txtPassword.TextMarginLeft = 3;
            this.txtPassword.TextMarginTop = 1;
            this.txtPassword.TextPlaceholder = "Enter Password";
            this.txtPassword.UseSystemPasswordChar = true;
            this.txtPassword.WordWrap = true;
            // 
            // txtUsername
            // 
            this.txtUsername.AcceptsReturn = false;
            this.txtUsername.AcceptsTab = false;
            this.txtUsername.AnimationSpeed = 200;
            this.txtUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsername.AutoSizeHeight = true;
            this.txtUsername.BackColor = System.Drawing.Color.Transparent;
            this.txtUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsername.BackgroundImage")));
            this.txtUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUsername.BorderRadius = 15;
            this.txtUsername.BorderThickness = 1;
            this.txtUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUsername.DefaultText = "";
            this.txtUsername.FillColor = System.Drawing.Color.White;
            this.txtUsername.HideSelection = true;
            this.txtUsername.IconLeft = global::DVLD_Project.Properties.Resources.Name_Icon__48;
            this.txtUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.IconPadding = 7;
            this.txtUsername.IconRight = null;
            this.txtUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.Lines = new string[0];
            this.txtUsername.Location = new System.Drawing.Point(217, 160);
            this.txtUsername.MaxLength = 32767;
            this.txtUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsername.Modified = false;
            this.txtUsername.Multiline = false;
            this.txtUsername.Name = "txtUsername";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsername.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnIdleState = stateProperties12;
            this.txtUsername.Padding = new System.Windows.Forms.Padding(3);
            this.txtUsername.PasswordChar = '\0';
            this.txtUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUsername.PlaceholderText = "Enter Username";
            this.txtUsername.ReadOnly = false;
            this.txtUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsername.SelectedText = "";
            this.txtUsername.SelectionLength = 0;
            this.txtUsername.SelectionStart = 0;
            this.txtUsername.ShortcutsEnabled = true;
            this.txtUsername.Size = new System.Drawing.Size(178, 39);
            this.txtUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsername.TabIndex = 10;
            this.txtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsername.TextMarginBottom = 0;
            this.txtUsername.TextMarginLeft = 3;
            this.txtUsername.TextMarginTop = 1;
            this.txtUsername.TextPlaceholder = "Enter Username";
            this.txtUsername.UseSystemPasswordChar = false;
            this.txtUsername.WordWrap = true;
            // 
            // lblUserIdValue
            // 
            this.lblUserIdValue.AllowParentOverrides = false;
            this.lblUserIdValue.AutoEllipsis = false;
            this.lblUserIdValue.CursorType = null;
            this.lblUserIdValue.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUserIdValue.Location = new System.Drawing.Point(217, 100);
            this.lblUserIdValue.Name = "lblUserIdValue";
            this.lblUserIdValue.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblUserIdValue.Size = new System.Drawing.Size(18, 17);
            this.lblUserIdValue.TabIndex = 9;
            this.lblUserIdValue.Text = "???";
            this.lblUserIdValue.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblUserIdValue.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // chkIsActive
            // 
            this.chkIsActive.AllowBindingControlAnimation = true;
            this.chkIsActive.AllowBindingControlColorChanges = false;
            this.chkIsActive.AllowBindingControlLocation = true;
            this.chkIsActive.AllowCheckBoxAnimation = false;
            this.chkIsActive.AllowCheckmarkAnimation = true;
            this.chkIsActive.AllowOnHoverStates = true;
            this.chkIsActive.AutoCheck = true;
            this.chkIsActive.BackColor = System.Drawing.Color.Transparent;
            this.chkIsActive.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chkIsActive.BackgroundImage")));
            this.chkIsActive.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chkIsActive.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chkIsActive.BorderRadius = 12;
            this.chkIsActive.Checked = true;
            this.chkIsActive.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
            this.chkIsActive.Cursor = System.Windows.Forms.Cursors.Default;
            this.chkIsActive.CustomCheckmarkImage = null;
            this.chkIsActive.Location = new System.Drawing.Point(214, 303);
            this.chkIsActive.MinimumSize = new System.Drawing.Size(17, 17);
            this.chkIsActive.Name = "chkIsActive";
            this.chkIsActive.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.chkIsActive.OnCheck.BorderRadius = 12;
            this.chkIsActive.OnCheck.BorderThickness = 2;
            this.chkIsActive.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.chkIsActive.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chkIsActive.OnCheck.CheckmarkThickness = 2;
            this.chkIsActive.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chkIsActive.OnDisable.BorderRadius = 12;
            this.chkIsActive.OnDisable.BorderThickness = 2;
            this.chkIsActive.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkIsActive.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chkIsActive.OnDisable.CheckmarkThickness = 2;
            this.chkIsActive.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkIsActive.OnHoverChecked.BorderRadius = 12;
            this.chkIsActive.OnHoverChecked.BorderThickness = 2;
            this.chkIsActive.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkIsActive.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chkIsActive.OnHoverChecked.CheckmarkThickness = 2;
            this.chkIsActive.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkIsActive.OnHoverUnchecked.BorderRadius = 12;
            this.chkIsActive.OnHoverUnchecked.BorderThickness = 1;
            this.chkIsActive.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkIsActive.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chkIsActive.OnUncheck.BorderRadius = 12;
            this.chkIsActive.OnUncheck.BorderThickness = 1;
            this.chkIsActive.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkIsActive.Size = new System.Drawing.Size(21, 21);
            this.chkIsActive.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chkIsActive.TabIndex = 8;
            this.chkIsActive.ThreeState = false;
            this.chkIsActive.ToolTipText = null;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(88, 305);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(85, 17);
            this.bunifuLabel2.TabIndex = 7;
            this.bunifuLabel2.Text = "User is active:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblPassword
            // 
            this.lblPassword.AllowParentOverrides = false;
            this.lblPassword.AutoEllipsis = false;
            this.lblPassword.CursorType = null;
            this.lblPassword.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPassword.Location = new System.Drawing.Point(111, 216);
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPassword.Size = new System.Drawing.Size(62, 17);
            this.lblPassword.TabIndex = 6;
            this.lblPassword.Text = "Password:";
            this.lblPassword.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPassword.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblUsername
            // 
            this.lblUsername.AllowParentOverrides = false;
            this.lblUsername.AutoEllipsis = false;
            this.lblUsername.CursorType = null;
            this.lblUsername.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUsername.Location = new System.Drawing.Point(111, 171);
            this.lblUsername.Name = "lblUsername";
            this.lblUsername.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblUsername.Size = new System.Drawing.Size(65, 17);
            this.lblUsername.TabIndex = 5;
            this.lblUsername.Text = "Username:";
            this.lblUsername.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblUsername.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblUserID
            // 
            this.lblUserID.AllowParentOverrides = false;
            this.lblUserID.AutoEllipsis = false;
            this.lblUserID.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblUserID.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblUserID.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUserID.Location = new System.Drawing.Point(127, 100);
            this.lblUserID.Name = "lblUserID";
            this.lblUserID.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblUserID.Size = new System.Drawing.Size(49, 17);
            this.lblUserID.TabIndex = 4;
            this.lblUserID.Text = "User ID:";
            this.lblUserID.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblUserID.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblAddNewUser2
            // 
            this.lblAddNewUser2.AllowParentOverrides = false;
            this.lblAddNewUser2.AutoEllipsis = false;
            this.lblAddNewUser2.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblAddNewUser2.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblAddNewUser2.Font = new System.Drawing.Font("Segoe UI", 21.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAddNewUser2.ForeColor = System.Drawing.Color.DodgerBlue;
            this.lblAddNewUser2.Location = new System.Drawing.Point(275, 37);
            this.lblAddNewUser2.Name = "lblAddNewUser2";
            this.lblAddNewUser2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblAddNewUser2.Size = new System.Drawing.Size(196, 40);
            this.lblAddNewUser2.TabIndex = 3;
            this.lblAddNewUser2.Text = "Add New User";
            this.lblAddNewUser2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblAddNewUser2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ucPersonInfoWithFilter1
            // 
            this.ucPersonInfoWithFilter1.BackColor = System.Drawing.Color.White;
            this.ucPersonInfoWithFilter1.Location = new System.Drawing.Point(22, 122);
            this.ucPersonInfoWithFilter1.Name = "ucPersonInfoWithFilter1";
            this.ucPersonInfoWithFilter1.Size = new System.Drawing.Size(710, 395);
            this.ucPersonInfoWithFilter1.TabIndex = 0;
            // 
            // frmAddEditUser
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.CancelButton = this.btnClose1;
            this.ClientSize = new System.Drawing.Size(759, 601);
            this.Controls.Add(this.tcAddEditUser);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "frmAddEditUser";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Add Edit User";
            this.Load += new System.EventHandler(this.frmAddEditUser_Load);
            this.tcAddEditUser.ResumeLayout(false);
            this.tpSelectPerson.ResumeLayout(false);
            this.tpSelectPerson.PerformLayout();
            this.tpLoginInfo.ResumeLayout(false);
            this.tpLoginInfo.PerformLayout();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPages tcAddEditUser;
        private System.Windows.Forms.TabPage tpSelectPerson;
        private System.Windows.Forms.TabPage tpLoginInfo;
        private People.Controls.ucPersonInfoWithFilter ucPersonInfoWithFilter1;
        private Bunifu.UI.WinForms.BunifuLabel lblSelectPerson;
        private Bunifu.UI.WinForms.BunifuLabel lblAddNewUser;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNext;
        private Bunifu.UI.WinForms.BunifuLabel lblUserID;
        private Bunifu.UI.WinForms.BunifuLabel lblAddNewUser2;
        private Bunifu.UI.WinForms.BunifuLabel lblUserIdValue;
        private Bunifu.UI.WinForms.BunifuCheckBox chkIsActive;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel lblPassword;
        private Bunifu.UI.WinForms.BunifuLabel lblUsername;
        private Bunifu.UI.WinForms.BunifuTextBox txtConfirmPassword;
        private Bunifu.UI.WinForms.BunifuLabel lblConfirmPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtUsername;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuLabel lblManagePeople;
        private Bunifu.UI.WinForms.BunifuCheckBox chkManagePeople;
        private Bunifu.UI.WinForms.BunifuLabel lblManageApplications;
        private Bunifu.UI.WinForms.BunifuCheckBox chkManageApplications;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuCheckBox chkManageUsers;
        private Bunifu.UI.WinForms.BunifuLabel lblPersonIDValue;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPrevious;
    }
}